apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: postgres
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      name: dbport
  selector:
    app: postgres
