apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: postgres
type: Opaque
data:
  postgres-user: {{ .Values.postgres.credentials.username | b64enc }}
  postgres-password: {{ .Values.postgres.credentials.password | b64enc }}
  postgres-db: {{ .Values.postgres.credentials.database | b64enc }}
