# Default values for app-chart.

app:
  replicaCount: 1
  image:
    repository: ghcr.io/pavanteja4333/gitops-demo-app
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
  environment: "dev"

postgres:
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  service:
    port: 5432
  credentials:
    username: dbadmin
    database: demodb
    # NOTE: In production, do not commit passwords to git.
    password: Password123!
